### ISSUE TITLE
sources tarballs available?

### ISSUE THREAD

**Issue by ScrumpyJack** [dimkr/logfence#1]
can you put logfense source tarball in http://dimkr.insomnia247.nl/sources/ ?

**Comment by dimkr** [comment]
RLSD doesn't have logfence, but RLSD 2 (https://github.com/dimkr/rlsd2) does.

**Comment by ScrumpyJack** [comment]
sure, but what I'm looking for is a release.

https://github.com/dimkr/logfence/releases

It's very helpful for packaging :)

**Comment by dimkr** [comment]
Done.
